version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: dockerfiles/dev.dockerfile
    volumes:
      - ./src:/src
      - ./README.rst:/src/README.rst
      - ./LICENSE:/src/LICENSE
  test311:
    build:
      context: .
      dockerfile: dockerfiles/dev.dockerfile
      args:
        PYTHON_VERSION: '3.11'
    command: pytest

  test312:
    build:
      context: .
      dockerfile: dockerfiles/dev.dockerfile
      args:
        PYTHON_VERSION: '3.12'
    command: pytest
